feat(camelCase/capitalize/kebabCase/lowerCase/snakeCase/startCase): improve return types
toss/es-toolkit pull request #313
Opened 2024-07-24 15:26 UTC by D-Sketon

2024-07-24 15:50 UTC, D-Sketon commented
close ＃172

2024-07-26 11:52 UTC, StyleShit requested changes

2024-07-26 11:52 UTC, StyleShit commented on src/string/_internal/getWords.ts
> +type LowercaseLetter = UppercaseLetter extends `${infer U}` ? Lowercase<U> : never;
why do you need the `extends` here?

```suggestion
type LowercaseLetter = Lowercase<UppercaseLetter>;
```

2024-07-26 11:52 UTC, StyleShit commented on src/string/capitalize.ts
> +export type Capitalize<T extends string> = T extends `${infer F}${infer R}` ? `${Uppercase<F>}${Lowercase<R>}` : T;
isn't it built in the language?

2024-07-26 11:52 UTC, StyleShit commented on src/string/_internal/getWords.ts
> +> = string extends T
maybe give those params better names to make it more readable?

2024-07-26 11:52 UTC, StyleShit commented on src/string/_internal/getWords.ts
> +export type CaseSplit<
is it possible to separate this huge type into a bunch of smaller ones?

2024-07-26 11:52 UTC, StyleShit commented on src/string/camelCase.spec.ts
> +    expectTypeOf(camelCase('    leading and trailing whitespace')).toEqualTypeOf<'leadingAndTrailingWhitespace'>();
```suggestion
    expectTypeOf(camelCase('    leading and trailing whitespace    ')).toEqualTypeOf<'leadingAndTrailingWhitespace'>();
```

2024-07-26 11:52 UTC, StyleShit commented on src/string/_internal/getWords.ts
> +  return Array.from(str.match(CASE_SPLIT_PATTERN) ?? []) as CaseSplit<T>;
I think you can do this:

```suggestion
  return Array.from(str.match(CASE_SPLIT_PATTERN) ?? []) as any;
```

or :

```suggestion
  return Array.from(str.match(CASE_SPLIT_PATTERN) ?? []) as never;
```

to make it shorter and easier to replace (now you'll have a single place to change if you'll have a slightly different return type)

WDYT?

2024-07-26 11:52 UTC, StyleShit commented on src/string/camelCase.ts
> +    return '' as CamelCase<T>;
same as above regarding the `as`, and also other places

2024-07-26 11:52 UTC, StyleShit commented on src/string/kebabCase.spec.ts
> +    expectTypeOf(kebabCase('    leading and trailing whitespace')).toEqualTypeOf<'leading-and-trailing-whitespace'>();
```suggestion
    expectTypeOf(kebabCase('    leading and trailing whitespace    ')).toEqualTypeOf<'leading-and-trailing-whitespace'>();
```

2024-07-26 11:52 UTC, StyleShit commented on src/string/lowerCase.spec.ts
> +    expectTypeOf(lowerCase('    leading and trailing whitespace')).toEqualTypeOf<'leading and trailing whitespace'>();
```suggestion
    expectTypeOf(lowerCase('    leading and trailing whitespace    ')).toEqualTypeOf<'leading and trailing whitespace'>();
```

2024-07-27 03:36 UTC, raon0211 commented
Hello, thanks for your contribution to our library! While I understand the reason of providing exact types, I am not sure they are worth it, considering maintainability and readability of complex types. Let me think a little bit about whether or not to include complex types to our library.

2024-09-13 06:33 UTC, raon0211 commented
Hello, thanks for your contribution. 

Since we value [simplicity of the implementation](https://github.com/toss/es-toolkit/blob/main/.github/CONTRIBUTING.md#12-simplicity), we decided not to merge complex types in our repository.

However, other types of contributions such as adding new functions would be really helpful for us. Looking forward to your next contribution.

2024-09-13 06:33 UTC, closed without merging